services:
  fsdb:
    image: postgres:latest
    container_name: Fivestar-database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432

  fsadmin:
    image: dpage/pgadmin4:latest
    container_name: Fivestar-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80

  fsapp:
    image: prawee/strapi:latest
    container_name: Fivestar-app
    environment:
      DATABASE_CLIENT: ${APP_CLIENT}
      DATABASE_HOST: ${APP_HOST}
      DATABASE_PORT: ${APP_DB_PORT}
      DATABASE_NAME: ${APP_NAME}
      DATABASE_USERNAME: ${APP_USER}
      DATABASE_PASSWORD: ${APP_PASSWORD}
    ports:
      - ${APP_PORT}:1337